### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by wwarby** [pushrocks/gulp-typings#4]
Hi, I've just upgraded from tsd to typings since tsd has been officially deprecated and I needed an equivalent replacement for gulp-tsd, so looked to this project. I think I have set it up exactly as described, but I'm getting an error when I run it:

```
[14:52:08] Starting 'typings'...
[14:52:08] Install TypeScript definition files
[14:52:09] 'typings' errored after 641 ms
[14:52:09] SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\gulp-typings\node_modules\beautylog\node_modules\hlight\index.js:93:57)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\gulp-typings\node_modules\beautylog\node_modules\hlight\node_modules\jsdom\lib\jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^
Process terminated with code 1.
```

**Comment by philkunz** [comment]
Does it install with the typings CLI?

**Comment by philkunz** [comment]
I think updating your node installation to LTS or stable should fix the issue. I don't support older node versions.

**Comment by wwarby** [comment]
Okay, I did have Node.js version 5.2.0 installed but I'm using Visual Studio 2015 to run Gulp tasks and it turns out Visual Studio uses it's own install of Node.js by default. I've upgraded to 5.8.0 and pointed Visual Studio at the same install, and I've got past that error, only to hit a different one which I'll raise a separate issue since is unrelated, though I've included the new error below for completeness.

`[08:42:35] 'typings' errored after 3.09 s
[08:42:35] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at Gulp.<anonymous> (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\Gulpfile.js:44:4)
    at module.exports (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:134:8)
    at C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
Process terminated with code 1.`
