### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by wwarby** [pushrocks/gulp-typings#5]
I am running on version 5.8.0 of Node.js, using Visual Studio 2015 as the execution host for Gulp tasks and I'm running what I think is a standard configuration of gulp-typings.

Here is my Gulp task definition:

```
var gulp = require('gulp');
var $ = require('gulp-load-plugins')({ lazy: true });
gulp.task('typings', function (done) {
	return gulp
		.src("./typings.json")
		.pipe($.typings); //This is line 44 referenced in the stack trace
});
```

And the error:

```
[08:42:35] 'typings' errored after 3.09 s
[08:42:35] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at Gulp.<anonymous> (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\Gulpfile.js:44:4)
    at module.exports (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\orchestrator\index.js:134:8)
    at C:\TFS\wwarby\AffordableHousing\NGIMS\Web\trunk\Hca.Ims.Web\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
Process terminated with code 1.
```

**Comment by philkunz** [comment]
Ok, I'm kind of unsure where this comes from. Do you have a Cloud9 Account? Then We could quickly test it together.

**Comment by wwarby** [comment]
I didn't have a Cloud9 account, but I have just set one up - I'm very willing to do whatever I can to help diagnose the problem but I can't put my actual project on a public website because it's a proprietary line of business application. Perhaps I could extract the relevant parts though. I'm not sure if the problem is related to Visual Studio on any way - I've never actually looked up how to execute a gulp task outside of the VS environment so I'll try that now and see if I get the same problem. Meanwhile let me know what you'd like me to do with Cloud9.

**Comment by philkunz** [comment]
I added node stable version to travis tests:
https://travis-ci.org/pushrocks/gulp-typings/jobs/116317707

Everything seems to run just fine.

**Comment by philkunz** [comment]
feel free to open a Cloud9 space, recreate your problem and send me a note of the workspacename to office@lossless.com.

 I will then take a quick look at it.

**Comment by wwarby** [comment]
Okay, I've ruled out Visual Studio as a cause - I can reproduce this in a command line window. I'll try to reproduce this on Cloud9 and get back to you.

**Comment by wwarby** [comment]
Issue reproduced at https://ide.c9.io/wwarby/gulp-typings-error
